packages:
  - 'oss/*'
  - 'packages/*'
  - 'apps/*'

catalog:
  # Shared production dependencies (used by 2+ packages)
  postgres: ^3.4.7
  ulid: ^3.0.0
  zod: ^3.25.56

catalogs:
  testing:
    '@types/jest': ^29.5.14
    jest: ^29.7.0
    ts-jest: ^29.3.4

  building:
    '@biomejs/biome': ^1.9.4
    '@types/node': ^22.15.30
    husky: ^9.1.7
    nx: ^22.0.3
    typescript: ^5.8.3
